version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Win32
build:
  project: SKY.sln
  verbosity: minimal

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive --remote
